# Generated by Django 5.2.1 on 2025-05-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_receptionist'),
    ]

    operations = [
    ]
