# Generated by Django 5.2.1 on 2025-05-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0006_receptionist_already_exists'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'hms_receptionist'
                ) THEN
                    -- Table does not exist, so we can create it normally
                    -- This will not execute since the table already exists
                    -- But we include it for completeness
                    RAISE NOTICE 'Table hms_receptionist does not exist. It would be created by the migration.';
                ELSE
                    RAISE NOTICE 'Table hms_receptionist already exists. Skipping creation.';
                END IF;
            END
            $$;
            ''',
            reverse_sql=''
        )
    ]
