# Generated by Django 5.2.1 on 2025-05-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_patientlabtestorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20),
        ),
    ]
