# Generated by Django 5.2.1 on 2025-05-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_update_gender_field'),
        ('patient_app', '0005_patientprofile_gender'),
    ]

    operations = [
    ]
